name: Workflow Overview

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  my_self_hosted_job:
    name: my self hosted job
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: selfHostedId
        name: Step in a Self hosted runner
        shell: sh
        run: |
          echo 'this is a multine comment'
          echo 'and this job has been executed from my self hosted runner'
  a_simple_job:
    if: false
    name: my Simple jobs name
    runs-on: ubuntu-latest
    steps:
      - id: stepId
        name: name of my step
        run: echo "this is the first step from the first job"
      - id: shellSTep
        name: step with another shell
        shell: python
        run: print('this step is using the python shell')
    
