name: Workflow Overview

on:
  workflow_dispatch

jobs:
  a_simple_job:
    name: my Simple jobs name
    runs-on: ubuntu-latest
    steps:
      - id: stepId
        name: name of my step
        run: echo "this is the first step from the first job"
      - id: shellSTep
        name: step with another shell
        shell: python
        run: print('this step is using the python shell')
    
